const HEADERS={"content-type":"application/json;charset=utf-8","access-control-allow-origin":"*","access-control-allow-methods":"GET,POST,OPTIONS","access-control-allow-headers":"content-type"};
const UA="Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile Safari/604.1";
const PLACE_CODE={"01":"札幌","02":"函館","03":"福島","04":"新潟","05":"東京","06":"中山","07":"中京","08":"京都","09":"阪神","10":"小倉"};
function json(obj,status=200){return new Response(JSON.stringify(obj),{status,headers:HEADERS});}
function ymd(d){const z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}${z(d.getMonth()+1)}${z(d.getDate())}`;}
function ymdSlash(s){return `${s.slice(0,4)}/${s.slice(4,6)}/${s.slice(6,8)}`;}
function strip(s=""){return String(s).replace(/<script[\s\S]*?<\/script>/gi,"").replace(/<style[\s\S]*?<\/style>/gi,"").replace(/<[^>]+>/g," ").replace(/&nbsp;/g," ").replace(/&amp;/g,"&").replace(/&#039;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g," ").trim();}
function raceNoFromId(id){return String(Number(String(id).slice(-2))||"");}
function placeFromRaceId(id){return PLACE_CODE[String(id).slice(4,6)]||"";}
async function fetchText(url){const r=await fetch(url,{headers:{"user-agent":UA,"accept-language":"ja,en-US;q=0.9","accept":"text/html,application/xhtml+xml"},cf:{cacheTtl:60}});if(!r.ok)throw new Error(`fetch ${r.status}`);return await r.text();}
function parseRaceIds(html){const ids=new Set();let m;const re=/race_id=(\d{12})/g;while((m=re.exec(html)))ids.add(m[1]);return [...ids].sort();}
function parseRaceName(html,raceNo){let t=strip((html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)||[])[1]||"").replace(/出馬表.*$/," ").replace(/\|.*$/," ").trim();const h1=(html.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i)||[])[1];if(h1)t=strip(h1)||t;return t||`${raceNo}R`;}
function parseRaceMeta(html,id,date){const raceNo=raceNoFromId(id),place=placeFromRaceId(id),text=strip(html),raceName=parseRaceName(html,raceNo);const surface=(text.match(/(芝|ダート|障害)\s*(\d{3,4})m/)||[])[1]||"";const dist=(text.match(/(?:芝|ダート|障害)\s*(\d{3,4})m/)||[])[1];const distance=dist?`${dist}m`:"";let grade="";const all=text+raceName;if(/G1|ＧⅠ|GI|GⅠ/.test(all))grade="G1";else if(/G2|ＧⅡ|GII|GⅡ/.test(all))grade="G2";else if(/G3|ＧⅢ|GIII|GⅢ/.test(all))grade="G3";else if(/リステッド|オープン|OP/.test(all))grade="OP";else if(/3勝|３勝/.test(all))grade="3勝";else if(/2勝|２勝/.test(all))grade="2勝";else if(/1勝|１勝/.test(all))grade="1勝";else if(/未勝利/.test(all))grade="未勝利";let age="";if(/4歳以上|４歳以上/.test(all))age="4歳以上";else if(/3歳以上|３歳以上/.test(all))age="3歳以上";else if(/3歳|３歳/.test(all))age="3歳";else if(/2歳|２歳/.test(all))age="2歳";let condition="";if(/ハンデ/.test(text))condition="ハンデ";else if(/別定/.test(text))condition="別定";else if(/定量/.test(text))condition="定量";else condition=grade||"";let sex=/牝/.test(all)?"牝馬":"混合";return {date:ymdSlash(date),place,raceNo,raceName,grade,condition,age,sex,surface,distance,headcount:""};}
function parseHorses(html){const horses=[];const rowRe=/<tr[^>]*>([\s\S]*?)<\/tr>/gi;let row;while((row=rowRe.exec(html))){const tr=row[1];if(!/horse\//i.test(tr)&&!/HorseInfo|HorseName|umalink|HorseList/i.test(tr))continue;const cells=[...tr.matchAll(/<td[^>]*>([\s\S]*?)<\/td>/gi)].map(x=>strip(x[1]));if(cells.length<3)continue;let no="",frame="",name="",odds="";for(const c of cells){if(!frame&&/^[1-8]$/.test(c))frame=c;if(!no&&/^\d{1,2}$/.test(c))no=c;}const nm=(tr.match(/<a[^>]+href=["'][^"']*horse[^"']*["'][^>]*>([\s\S]*?)<\/a>/i)||[])[1];if(nm)name=strip(nm);if(!name){const cand=cells.find(c=>/[ァ-ヶー一-龠]/.test(c)&&!/(牡|牝|セ|kg|歳|人気|取消|除外)/.test(c)&&c.length>=2);if(cand)name=cand;}const oddsCand=cells.find(c=>/^\d+(\.\d+)?$/.test(c)&&Number(c)>1&&Number(c)<999);if(oddsCand)odds=oddsCand;if(no&&name)horses.push({frame:frame||String(Math.ceil(Number(no)/2)),no,name,last1:"",last2:"",last3:"",odds});}const unique=[],seen=new Set();for(const h of horses){if(seen.has(h.no))continue;seen.add(h.no);unique.push(h);}unique.sort((a,b)=>Number(a.no)-Number(b.no));return unique;}
function addPopularity(horses){const vals=horses.map((h,i)=>({i,odds:Number(h.odds)})).filter(x=>Number.isFinite(x.odds)&&x.odds>0).sort((a,b)=>a.odds-b.odds);let rank=1,prev=null,count=0;for(const v of vals){count++;if(prev!==null&&v.odds!==prev)rank=count;horses[v.i].popularity=String(rank);prev=v.odds;}return horses;}
async function raceDetail(id,date){const url=`https://race.netkeiba.com/race/shutuba.html?race_id=${id}&rf=race_list`;const html=await fetchText(url);const race=parseRaceMeta(html,id,date||String(id).slice(0,8));const horses=addPopularity(parseHorses(html));race.headcount=String(horses.length||"");return {id:`${race.date}_${race.place}_${String(race.raceNo).padStart(2,'0')}_${id}`,race,horses,source:"netkeiba-real",sourceUrl:url,raceId:id};}
async function scheduleForDate(date){const url=`https://race.netkeiba.com/top/race_list.html?kaisai_date=${date}`;const html=await fetchText(url);const ids=parseRaceIds(html);const races=[];for(const id of ids.slice(0,72)){try{races.push(await raceDetail(id,date));}catch(e){const raceNo=raceNoFromId(id),place=placeFromRaceId(id);races.push({id:`${ymdSlash(date)}_${place}_${String(raceNo).padStart(2,'0')}_${id}`,race:{date:ymdSlash(date),place,raceNo,raceName:`${place}${raceNo}R`,grade:"",condition:"",age:"",sex:"",surface:"",distance:"",headcount:""},horses:[],source:"netkeiba-real-list-only",raceId:id,error:String(e.message||e)});}}return races;}
function nextDays(start,days){const arr=[];const d=new Date(start);for(let i=0;i<days;i++){const x=new Date(d);x.setDate(d.getDate()+i);arr.push(ymd(x));}return arr;}
export default{async fetch(request){if(request.method==="OPTIONS")return json({ok:true});const url=new URL(request.url);try{if(url.pathname==="/api/health")return json({ok:true,worker:"rev-realdata-schedule",time:new Date().toISOString()});if(url.pathname==="/api/race"){const id=url.searchParams.get("race_id");if(!id)return json({ok:false,error:"race_id required"},400);return json({ok:true,race:await raceDetail(id,String(id).slice(0,8))});}if(url.pathname!=="/api/schedule")return json({ok:false,error:"not found"},404);const qdate=url.searchParams.get("date");const days=Math.min(Number(url.searchParams.get("days")||9),16);const start=qdate&&/^\d{8}$/.test(qdate)?qdate:ymd(new Date());const dates=nextDays(`${start.slice(0,4)}-${start.slice(4,6)}-${start.slice(6,8)}T00:00:00+09:00`,days);let races=[];const errors=[];for(const d of dates){try{races=races.concat(await scheduleForDate(d));}catch(e){errors.push({date:d,error:String(e.message||e)});}if(races.length>=108)break;}return json({ok:true,realData:true,count:races.length,generatedAt:new Date().toISOString(),dates,errors,races});}catch(e){return json({ok:false,error:String(e.message||e),hint:"netkeibaのHTML構造変更・アクセス制限・開催日違いの場合があります。/api/schedule?date=YYYYMMDD で開催日指定してください。"},500);}}};
